#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <format>
#include <memory>
#include <mutex>
#include <print>
#include <string>

#include "../main.hh"

#include "los.hh"

#include "hata.hh"
#include "thread_pool.hh"

#include "../common.h"

#include "cost.hh"
#include "ecc33.hh"
#include "egli.hh"
#include "ericsson.hh"
#include "fspl.hh"
#include "itwom3.0.hh"
#include "pel.hh"
#include "soil.hh"
#include "sui.hh"

enum : std::uint8_t { NUM_SECTIONS = 4 };

namespace {
	std::mutex maskMutex;
	bool ***processed;
	bool has_init_processed = false;

	void init_processed()
	{
		const std::scoped_lock l (maskMutex);
		if (!has_init_processed) {
			has_init_processed = true;

			processed = new bool **[MAXPAGES];
			for (int i = 0; i < MAXPAGES; i++) {
				processed[i] = new bool *[ippd];
				for (int x = 0; x < ippd; x++) {
					processed[i][x] = new bool [ippd];
					for (int y = 0; y < ippd; y++) {
						processed[i][x][y] = false;
					}
				}
			}
		}

		has_init_processed = true;
	}

	auto can_process(double lat, double lon) -> bool
	{
		/* Lines, text, markings, and coverage areas are stored in a
		mask that is combined with topology data when topographic
		maps are generated by ss.  This function sets bits in
		the mask based on the latitude and longitude of the area
		pointed to. */

		for (int indx = 0; indx < MAXPAGES; ++indx) {
			const int x = static_cast<int>(std::rint(ppd * (lat - dem[indx].min_north)));
			const int y = mpi - static_cast<int>(std::rint(yppd * (LonDiff(dem[indx].max_west, lon))));

			if (x >= 0 && x <= mpi && y >= 0 && y <= mpi) {
				/* As long as we only set this without resetting it we can
				 check outside a mutex first without worrying about race
				 conditions. But we must lock the mutex before updating the
				 value. */

				if(!processed[indx][x][y]) {
					const std::scoped_lock l (maskMutex);
					if(!processed[indx][x][y]) {
						processed[indx][x][y] = true;
						return true;
					}
				}
			}
		}
		return false;
	}
} /* anonymous namespace */

void LOS::rangePropagation(std::shared_ptr<propagationRange> v)
{
	if(!has_init_processed)  {
		init_processed();
	}

	//if(v->use_threads) {
	//	alloc_elev();
	//	alloc_path();
	//}

	const double minwest = dpp + v->min_west;
	double lon = v->eastwest ? minwest : v->min_west;
	double lat = v->min_north;
	int y = 0;

	do {
		if (lon >= 360.0) {
			lon -= 360.0;
		}

		site_t edge;
		edge.lat = lat;
		edge.lon = lon;
		edge.alt = v->altitude;

		if(v->los) {
			PlotLOSPath(v->source, edge, v->mask_value);
		}
		else {
			auto _ = PlotPropPath(v->source, edge, v->mask_value, v->fd, v->propmodel, v->knifeedge, v->pmenv);
		}

		++y;
		if(v->eastwest) {
			lon = minwest + (dpp * y);
		}
		else {
			lat = v->min_north + (dpp * y);
		}


	} while ( v->eastwest ? (LonDiff(lon, v->max_west) <= 0.0) : (lat < v->max_north) );

	//if(v->use_threads) {
	//	free_elev();
	//	free_path();
	//}
}

void LOS::PlotLOSPath(const struct site_t& source, const struct site_t& destination, unsigned char mask_value)
{
	/* This function analyzes the path between the source and
	   destination locations.  It determines which points along
	   the path have line-of-sight visibility to the source.
	   Points along with path having line-of-sight visibility
	   to the source at an AGL altitude equal to that of the
	   destination location are stored by setting bit 1 in the
	   mask[][] array, which are displayed in green when PPM
	   maps are later generated by ss. */

	auto path = ReadPath(source, destination);
	for (int y = 0; (y < (path.length - 1) && path.distance[y] <= max_range); y++) {
	//for (y = 0; y < path.length; y++) {
		/* Test this point only if it hasn't been already
		   tested and found to be free of obstructions. */

		if ((GetMask(path.lat[y], path.lon[y]) & mask_value) == 0
			&& can_process(path.lat[y], path.lon[y])) {

			double distance = FEET_PER_MILE * path.distance[y];
			double tx_alt = earthradius + source.alt + path.elevation[0];
			double rx_alt =
			    earthradius + destination.alt + path.elevation[y];

			/* Calculate the cosine of the elevation of the
			   transmitter as seen at the temp rx point. */

			double cos_xmtr_angle =
			    ((rx_alt * rx_alt) + (distance * distance) -
			     (tx_alt * tx_alt)) / (2.0 * rx_alt * distance);

			bool block = false;
			for (int x = y; x >= 0 && !block; x--) {
				distance =
				    FEET_PER_MILE * (path.distance[y] -
					      path.distance[x]);
				double test_alt =
				    earthradius + (path.elevation[x] ==
						   0.0 ? path.
						   elevation[x] : path.
						   elevation[x] + clutter);

				double cos_test_angle =
				    ((rx_alt * rx_alt) + (distance * distance) -
				     (test_alt * test_alt)) / (2.0 * rx_alt *
							       distance);

				/* Compare these two angles to determine if
				   an obstruction exists.  Since we're comparing
				   the cosines of these angles rather than
				   the angles themselves, the following "if"
				   statement is reversed from what it would
				   be if the actual angles were compared. */

				if (cos_xmtr_angle >= cos_test_angle) {
					block = true;
				}
			}

			if (!block) {
				OrMask(path.lat[y], path.lon[y], mask_value);
			}
		}
	}
}

auto LOS::PlotPropPath(const struct site_t& source, const struct site_t& destination,
		  unsigned char mask_value, FILE * fd, int propmodel,
		  int knifeedge, int pmenv) -> std::vector<double>
{

	int y, ifs, ofs, errnum;
	char block = 0;
	std::string strmode;
	double loss, azimuth, pattern = 0.0,
	    xmtr_alt, dest_alt, xmtr_alt2, dest_alt2,
	    cos_rcvr_angle, cos_test_angle = 0.0, test_alt,
	    elevation = 0.0, distance = 0.0,
	    field_strength = 0.0, rxp, dBm, diffloss;
	struct site_t temp;
	float dkm;
	std::vector<double> elev(ARRAYSIZE + 10);

	auto path = ReadPath(source, destination);

	const double four_thirds_earth = FOUR_THIRDS * EARTHRADIUS_FT;

	for (int x = 1; x < path.length - 1; x++) {
		elev[x + 2] =
		    (path.elevation[x] ==
		     0.0 ? path.elevation[x] * METERS_PER_FOOT : (clutter + path.elevation[x]) * METERS_PER_FOOT);
	}

	/* Copy ending points without clutter */

	elev[2] = path.elevation[0] * METERS_PER_FOOT;

	elev[path.length + 1] =
	    path.elevation[path.length - 1] * METERS_PER_FOOT;

	/* Since the only energy the Longley-Rice model considers
	   reaching the destination is based on what is scattered
	   or deflected from the first obstruction along the path,
	   we first need to find the location and elevation angle
	   of that first obstruction (if it exists).  This is done
	   using a 4/3rds Earth radius to match the model used by
	   Longley-Rice.  This information is required for properly
	   integrating the antenna's elevation pattern into the
	   calculation for overall path loss. */
	//if(debug)
	//	fprintf(stderr,"four_thirds_earth %.1f source.alt %.1f path.elevation[0] %.1f\n",four_thirds_earth,source.alt,path.elevation[0]);
	for (y = 2; (y < (path.length - 1) && path.distance[y] <= max_range); y++) {
		/* Process this point only if it
		   has not already been processed. */

		if ( (GetMask(path.lat[y], path.lon[y]) & 248) !=
			(mask_value << 3) && can_process(path.lat[y], path.lon[y])) {

			std::string fd_buffer;

			distance = FEET_PER_MILE * path.distance[y];
			xmtr_alt =
			    four_thirds_earth + source.alt + path.elevation[0];
			dest_alt =
			    four_thirds_earth + destination.alt +
			    path.elevation[y];
			dest_alt2 = dest_alt * dest_alt;
			xmtr_alt2 = xmtr_alt * xmtr_alt;

			/* Calculate the cosine of the elevation of
			   the receiver as seen by the transmitter. */

			cos_rcvr_angle =
			    ((xmtr_alt2) + (distance * distance) -
			     (dest_alt2)) / (2.0 * xmtr_alt * distance);

			cos_rcvr_angle = std::clamp(cos_rcvr_angle, -1.0, 1.0);

			if (got_elevation_pattern || fd != nullptr) {
				/* Determine the elevation angle to the first obstruction
				   along the path IF elevation pattern data is available
				   or an output (.ano) file has been designated. */

				for (int x = 2, block = 0; (x < y && block == 0); x++) {
					distance = FEET_PER_MILE * path.distance[x];

					test_alt =
					    four_thirds_earth +
					    (path.elevation[x] ==
					     0.0 ? path.elevation[x] : path.
					     elevation[x] + clutter);

					/* Calculate the cosine of the elevation
					   angle of the terrain (test point)
					   as seen by the transmitter. */

					cos_test_angle =
					    ((xmtr_alt2) +
					     (distance * distance) -
					     (test_alt * test_alt)) / (2.0 *
								       xmtr_alt
								       *
								       distance);

					cos_test_angle = std::clamp(cos_test_angle, -1.0, 1.0);

					/* Compare these two angles to determine if
					   an obstruction exists.  Since we're comparing
					   the cosines of these angles rather than
					   the angles themselves, the sense of the
					   following "if" statement is reversed from
					   what it would be if the angles themselves
					   were compared. */

					if (cos_rcvr_angle >= cos_test_angle) {
						block = 1;
					}
				}

				if (block != 0) {
					elevation =  (std::acos(cos_test_angle) * RAD2DEG) - 90.0;
				}
				else {
					elevation = (std::acos(cos_rcvr_angle) * RAD2DEG) - 90.0;
				}
			}

			/* Determine attenuation for each point along the
			   path using a prop model starting at y=2 (number_of_points = 1), the
			   shortest distance terrain can play a role in
			   path loss. */

			elev[0] = y - 1;	/* (number of points - 1) */

			/* Distance between elevation samples */

			elev[1] =
			    METERS_PER_MILE * (path.distance[y] -
					       path.distance[y - 1]);

			path.elevation[y] = std::max(path.elevation[y], 1.0);

			dkm = (elev[1] * elev[0]) * 0.001;	// km

			switch (propmodel) {
			case 1:
				// Longley Rice ITM
				ITWOM3::point_to_point_ITM(source.alt * METERS_PER_FOOT,
						   destination.alt *
						   METERS_PER_FOOT,
						   LR.eps_dielect,
						   LR.sgm_conductivity,
						   LR.eno_ns_surfref,
						   LR.frq_mhz, LR.radio_climate,
						   LR.pol, LR.conf, LR.rel, elev,
						   loss, strmode, errnum);
				break;
			case 3:
				//HATA 1, 2 & 3
				loss =
				    HATApathLoss(LR.frq_mhz, source.alt * METERS_PER_FOOT,
						(path.elevation[y] * METERS_PER_FOOT) +	 (destination.alt * METERS_PER_FOOT), dkm, pmenv);
				break;
			case 4:
				// ECC33
				loss =
				    ECC33pathLoss(LR.frq_mhz, source.alt * METERS_PER_FOOT,
						(path.elevation[y] *
						 METERS_PER_FOOT) +
						  (destination.alt *
						   METERS_PER_FOOT), dkm,
						  pmenv);
				break;
			case 5:
				// SUI
				loss =
				    SUIpathLoss(LR.frq_mhz, source.alt * METERS_PER_FOOT,
						(path.elevation[y] *
						 METERS_PER_FOOT) +
						(destination.alt *
						 METERS_PER_FOOT), dkm, pmenv);
				break;
			case 6:
				// COST231-Hata
				loss =
				    COST231pathLoss(LR.frq_mhz, source.alt * METERS_PER_FOOT,
						(path.elevation[y] *
						 METERS_PER_FOOT) +
						    (destination.alt *
						     METERS_PER_FOOT), dkm,
						    pmenv);
				break;
			case 7:
				// ITU-R P.525 Free space path loss
				loss = FSPLpathLoss(LR.frq_mhz, dkm);
				break;
			case 8:
				// ITWOM 3.0
				ITWOM3::point_to_point(source.alt * METERS_PER_FOOT,
					       destination.alt *
					       METERS_PER_FOOT, LR.eps_dielect,
					       LR.sgm_conductivity,

					       LR.eno_ns_surfref, LR.frq_mhz,
					       LR.radio_climate, LR.pol,
					       LR.conf, LR.rel, elev,
					       loss, strmode, errnum);
				break;
			case 9:
				// Ericsson
				loss =
				    EricssonpathLoss(LR.frq_mhz, source.alt * METERS_PER_FOOT,
						(path.elevation[y] *
						 METERS_PER_FOOT) +
						     (destination.alt *
						      METERS_PER_FOOT), dkm,
						     pmenv);
				break;
			case 10:
				// Plane earth
				loss =	PlaneEarthLoss(dkm, source.alt * METERS_PER_FOOT, (path.elevation[y] * METERS_PER_FOOT) + (destination.alt * METERS_PER_FOOT));
				break;
			case 11:
				// Egli VHF/UHF
				loss = EgliPathLoss(LR.frq_mhz, source.alt * METERS_PER_FOOT, (path.elevation[y] * METERS_PER_FOOT) + (destination.alt * METERS_PER_FOOT),dkm);
				break;
			case 12:
				// Soil
				loss = SoilPathLoss(LR.frq_mhz, dkm, LR.eps_dielect);
				break;


			default:
				ITWOM3::point_to_point_ITM(source.alt * METERS_PER_FOOT,
						   destination.alt *
						   METERS_PER_FOOT,
						   LR.eps_dielect,
						   LR.sgm_conductivity,
						   LR.eno_ns_surfref,
						   LR.frq_mhz, LR.radio_climate,
						   LR.pol, LR.conf, LR.rel, elev,
						   loss, strmode, errnum);

			}


			if (knifeedge == 1 && propmodel > 1) {
				diffloss = ked(LR.frq_mhz, destination.alt * METERS_PER_FOOT, dkm, elev);
				loss += (diffloss);	// ;)
			}
			//Key stage. Link dB for p2p is returned as 'loss'.

			temp.lat = path.lat[y];
			temp.lon = path.lon[y];

			azimuth = Azimuth(source, temp);

			if (fd != nullptr) {
				fd_buffer += std::format("{:.7f}, {:.7f}, {:.3f}, {:.3f}, ",
					path.lat[y], path.lon[y], azimuth, elevation);
			}

			/* If ERP==0, write path loss to alphanumeric
			   output file.  Otherwise, write field strength
			   or received power level (below), as appropriate. */

			if (fd != nullptr && LR.erp == 0.0) {
				fd_buffer += std::format("{:.2f}", loss);
			}

			/* Integrate the antenna's radiation
			   pattern into the overall path loss. */

			int x = static_cast<int>(std::rint(10.0 * (10.0 - elevation)));

			if (x >= 0 && x <= 1000) {
				azimuth = std::rint(azimuth);

				pattern =
				    static_cast<double>(LR.antenna_pattern[static_cast<int>(azimuth)][x]);

				if (pattern != 0.0) {
					pattern = 20.0 * std::log10(pattern);
					loss -= pattern;
				}
			}

			if (LR.erp != 0.0) {
				if (dbm) {
					/* dBm is based on EIRP (ERP + 2.14) */

					rxp =
					    LR.erp /
					    (std::pow(10.0, (loss - 2.14) / 10.0));

					dBm = 10.0 * (std::log10(rxp * 1000.0));

					if (fd != nullptr) {
						fd_buffer += std::format("{:.3f}", dBm);
					}

					/* Scale roughly between 0 and 255 */

					ifs = std::clamp(200 + static_cast<int>(std::rint(dBm)), 0, 255);

					ofs = GetSignal(path.lat[y], path.lon[y]);

					ifs = std::max(ifs, ofs);

					PutSignal(path.lat[y], path.lon[y],
						  static_cast<unsigned char>(ifs));

				}

				else {
					field_strength =
					    (139.4 +
					     (20.0 * std::log10(LR.frq_mhz)) -
					     loss) +
					    (10.0 * std::log10(LR.erp / 1000.0));

					ifs = std::clamp(100 + static_cast<int>(std::rint(field_strength)), 0, 255);

					ofs = GetSignal(path.lat[y], path.lon[y]);

					ifs = std::max(ifs, ofs);

					PutSignal(path.lat[y], path.lon[y],
						  static_cast<unsigned char>(ifs));

					if (fd != nullptr) {
						fd_buffer += std::format("{:.3f}", field_strength);
					}
				}
			}

			else {
				if (loss > 255) {
					ifs = 255;
				}
				else {
					ifs = static_cast<int>(std::rint(loss));
				}
				
				ofs = GetSignal(path.lat[y], path.lon[y]);

				if (ofs != 0) {
					ifs = std::min(ifs, ofs);
				}

				PutSignal(path.lat[y], path.lon[y],
					  static_cast<unsigned char>(ifs));
			}

			if (fd != nullptr) {
				if (block != 0U) {
					fd_buffer += " *";
				}
				std::println(fd, "{}", fd_buffer);
			}

			/* Mark this point as having been analyzed */

			PutMask(path.lat[y], path.lon[y],
				(GetMask(path.lat[y], path.lon[y]) & 7) +
				(mask_value << 3));
		}
	}

	cropLat = std::max(path.lat[y], cropLat);

	// TODO: This seems like a bug
	cropLon = std::max<double>(y, cropLon);

	//if(cropLon>180)
	//	cropLon-=360;
	return elev;
}

void LOS::PlotLOSMap(const struct site_t& source, double altitude, const std::string& plo_filename, bool use_threads)
{
	/* This function performs a 360 degree sweep around the
	   transmitter site (source location), and plots the
	   line-of-sight coverage of the transmitter on the ss
	   generated topographic map based on a receiver located
	   at the specified altitude (in feet AGL).  Results
	   are stored in memory, and written out in the form
	   of a topographic map when the WritePPM() function
	   is later invoked. */

	static thread_local unsigned char mask_value = 1;
	thread_pool threads(use_threads ? NUM_SECTIONS : 1);

	FILE *fd = nullptr;

	if (!plo_filename.empty()) {
		fd = fopen(plo_filename.data(), "wb");
	}

	if (fd != nullptr) {
		std::println(fd,
			"{:.3f}, {:.3f}\t; max_west, min_west\n{:.3f}, {:.3f}\t; max_north, min_north",
			max_west, min_west, max_north, min_north);
	}

	// Four sections start here
	// Process north edge east/west, east edge north/south,
	// south edge east/west, west edge north/south
	std::array<double, 4> range_min_west = {min_west, min_west, min_west, max_west};
	std::array<double, 4> range_min_north = {max_north, min_north, min_north, min_north};
	std::array<double, 4> range_max_west = {max_west, min_west, max_west, max_west};
	std::array<double, 4> range_max_north = {max_north, max_north, min_north, max_north};
	std::array<std::shared_ptr<propagationRange>, NUM_SECTIONS> r;

	for(int i = 0; i < NUM_SECTIONS; ++i) {
		auto range = std::make_shared<propagationRange>();
		r[i] = range;
		range->los = true;

		range->eastwest = (range_min_west[i] != range_max_west[i]);
		range->min_west = range_min_west[i];
		range->max_west = range_max_west[i];
		range->min_north = range_min_north[i];
		range->max_north = range_max_north[i];

		range->use_threads = use_threads;
		range->altitude = altitude;
		range->source = source;
		range->mask_value = mask_value;
		range->fd = fd;

		thread_pool::post(threads, [&range]() { rangePropagation(range); });
	}

	switch (mask_value) {
	case 1:
		mask_value = 8;
		break;

	case 8:
		mask_value = 16;
		break;

	case 16:
		mask_value = 32;
	}
}

void LOS::PlotPropagation(struct site_t source, double altitude, const std::string& plo_filename,
		     int propmodel, int knifeedge, int haf, int pmenv, bool use_threads)
{
	static thread_local unsigned char mask_value = 1;
	thread_pool threads(use_threads ? NUM_SECTIONS : 1);
	FILE *fd = nullptr;
	
	if (LR.erp == 0.0 && debug) {
		std::print(stderr, "path loss");
	}
	else {
		if (debug) {
			if (dbm) {
				std::print(stderr, "signal power level");
			}
			else {
				std::print(stderr, "field strength");
			}
		}
	}
	if (debug) {
		std::println(stderr,
			" contours of \"{}\" out to a radius of {:.2f} {} with Rx antenna(s) at {:.2f} {} AGL",
			source.name,
			metric ? max_range * KM_PER_MILE : max_range,
			metric ? "kilometers" : "miles",
			metric ? altitude * METERS_PER_FOOT : altitude,
			metric ? "meters" : "feet");
	}

	if (clutter > 0.0 && debug) {
		std::print(stderr, "\nand {:.2f} {} of ground clutter",
			metric ? clutter * METERS_PER_FOOT : clutter,
			metric ? "meters" : "feet");
	}

	if (!plo_filename.empty()) {
		fd = fopen(plo_filename.data(), "wb");
	}

	if (fd != nullptr) {
		std::println(fd,
			"{:.3f}, {:.3f}\t; max_west, min_west\n{:.3f}, {:.3f}\t; max_north, min_north",
			max_west, min_west, max_north, min_north);
	}

	
	// Four sections start here
	// Process north edge east/west, east edge north/south,
	// south edge east/west, west edge north/south
	std::array<double, 4> range_min_west = {min_west, min_west, min_west, max_west};
	std::array<double, 4> range_min_north = {max_north, min_north, min_north, min_north};
	std::array<double, 4> range_max_west = {max_west, min_west, max_west, max_west};
	std::array<double, 4> range_max_north = {max_north, max_north, min_north, max_north};
	std::array<std::shared_ptr<propagationRange>, NUM_SECTIONS> r;

	for(int i = 0; i < NUM_SECTIONS; ++i) {
		auto range = std::make_shared<propagationRange>();
		r[i] = range;
		range->los = false;

		// Only process correct half
		if((NUM_SECTIONS - i) <= (NUM_SECTIONS / 2) && haf == 1) {
			continue;
		}
		if((NUM_SECTIONS - i) > (NUM_SECTIONS / 2) && haf == 2) {
			continue;
		}


		range->eastwest = (range_min_west[i] != range_max_west[i]);
		range->min_west = range_min_west[i];
		range->max_west = range_max_west[i];
		range->min_north = range_min_north[i];
		range->max_north = range_max_north[i];

		range->use_threads = use_threads;
		range->altitude = altitude;
		range->source = source;
		range->mask_value = mask_value;
		range->fd = fd;
		range->propmodel = propmodel;
		range->knifeedge = knifeedge;
		range->pmenv = pmenv;

		thread_pool::post(threads, [&range]() { rangePropagation(range); });

	}

	if (fd != nullptr) {
		fclose(fd);
	}

	if (mask_value < 30) {
		mask_value++;
	}
}

void LOS::PlotPath(const struct site_t& source, const struct site_t& destination, char mask_value)
{
	/* This function analyzes the path between the source and
	   destination locations.  It determines which points along
	   the path have line-of-sight visibility to the source.
	   Points along with path having line-of-sight visibility
	   to the source at an AGL altitude equal to that of the
	   destination location are stored by setting bit 1 in the
	   mask[][] array, which are displayed in green when PPM
	   maps are later generated by SPLAT!. */

	auto path = ReadPath(source, destination);

	for (int y = 0; y < path.length; y++) {
		/* Test this point only if it hasn't been already
		   tested and found to be free of obstructions. */

		if ((GetMask(path.lat[y], path.lon[y]) & mask_value) == 0) {
			double distance = FEET_PER_MILE * path.distance[y];
			const double tx_alt = earthradius + source.alt + path.elevation[0];
			const double rx_alt =
			    earthradius + destination.alt + path.elevation[y];

			/* Calculate the cosine of the elevation of the
			   transmitter as seen at the temp rx point. */

			const double cos_xmtr_angle =
			    ((rx_alt * rx_alt) + (distance * distance) -
			     (tx_alt * tx_alt)) / (2.0 * rx_alt * distance);

			bool block = false;
			//TODO: Use a std::ranges algo like none_of
			for (int x = y; x >= 0 && !block; x--) {
				distance =
				    FEET_PER_MILE * (path.distance[y] -
					      path.distance[x]);
				const double test_alt =
				    earthradius + (path.elevation[x] ==
						   0.0 ? path.
						   elevation[x] : path.
						   elevation[x] + clutter);

				const double cos_test_angle =
					((rx_alt * rx_alt) + (distance * distance) - (test_alt * test_alt)) / (2.0 * rx_alt * distance);

				/* Compare these two angles to determine if
				   an obstruction exists.  Since we're comparing
				   the cosines of these angles rather than
				   the angles themselves, the following "if"
				   statement is reversed from what it would
				   be if the actual angles were compared. */

				if (cos_xmtr_angle >= cos_test_angle) {
					block = true;
				}
			}

			if(!block) {
				OrMask(path.lat[y], path.lon[y], mask_value);
			}
		}
	}
}
