const double version = 3.21;
/****************************************************************************\
*  Signal Server: Radio propagation simulator by Alex Farrant QCVS, 2E0TDW   *
******************************************************************************
*    SPLAT! Project started in 1997 by John A. Magliacane, KD2BD             *
******************************************************************************
*         Please consult the SPLAT! documentation for a complete list of     *
*         individuals who have contributed to this project.                  *
******************************************************************************
*                                                                            *
*  This program is free software; you can redistribute it and/or modify it   *
*  under the terms of the GNU General Public License as published by the     *
*  Free Software Foundation; either version 2 of the License or any later    *
*  version.                                                                  *
*                                                                            *
*  This program is distributed in the hope that it will useful, but WITHOUT  *
*  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or     *
*  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License     *
*  for more details.                                                         *
*                                                                            *
\****************************************************************************/

#include <algorithm>
#include <cctype>
#include <cerrno>
#include <charconv>
#include <climits>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <format>
#include <numbers>
#include <print>
#include <string>
#include <string_view>

#include "common.h"
#include "inputs.hh"
#include "main.hh"
#include "outputs.hh"

#include "models/los.hh"

int MAXPAGES = 10*10;
int IPPD = 1200;
int ARRAYSIZE = (MAXPAGES * IPPD) + 10;

std::string sdf_path;

double earthradius, max_range = 0.0, dpp, ppd, yppd,
    fzone_clearance = 0.6, clutter, tercon, terdic,
    east, west,
    min_north = 90, max_north = -90, min_west = 360, max_west = -1,
    westoffset=180, eastoffset=-180, delta=0, rxGain=0, antenna_rotation,
    antenna_downtilt,antenna_dt_direction, cropLat=-70, cropLon=0;

int ippd, mpi, max_elevation = -32768, min_elevation = 32768,
    contour_threshold, pred, pblue, pgreen, ter, multiplier = 256,
    jgets = 0, MAXRAD, hottest = 0;
int resample = 0;

unsigned char got_elevation_pattern, got_azimuth_pattern;
bool debug = false;
bool metric = false;
bool dbm = false;

//thread_local double *elev;
//thread_local struct path_t path;
struct site_t tx_site[2];
struct dem_t *dem;

struct LR_t LR;
struct region_t region;

constexpr auto arccos(double x, double y) -> double
{
	/* This function implements the arc cosine function,
	   returning a value between 0 and TWOPI. */

	if (y > 0.0) {
		return std::acos(x / y);
	}

	if (y < 0.0) {
		return std::numbers::pi + std::acos(x / y);
	}

	return 0.0;
}

auto PutMask(double lat, double lon, int value) -> int
{
	/* Lines, text, markings, and coverage areas are stored in a
	   mask that is combined with topology data when topographic
	   maps are generated by ss.  This function sets and resets
	   bits in the mask based on the latitude and longitude of the
	   area pointed to. */

	for (int indx = 0;indx < MAXPAGES; ++indx) {
		const int x = static_cast<int>(std::rint(ppd * (lat - dem[indx].min_north)));
		const int y = mpi - static_cast<int>(std::rint(yppd * (LonDiff(dem[indx].max_west, lon))));

		if (x >= 0 && x <= mpi && y >= 0 && y <= mpi) {
			dem[indx].mask[x][y] = value;
			return static_cast<int>(dem[indx].mask[x][y]);
		}
	}

	return -1;
}

auto OrMask(double lat, double lon, int value) -> int
{
	/* Lines, text, markings, and coverage areas are stored in a
	   mask that is combined with topology data when topographic
	   maps are generated by ss.  This function sets bits in
	   the mask based on the latitude and longitude of the area
	   pointed to. */

	for (int indx = 0; indx < MAXPAGES; ++indx) {
		const int x = static_cast<int>(std::rint(ppd * (lat - dem[indx].min_north)));
		const int y = mpi - static_cast<int>(std::rint(yppd * (LonDiff(dem[indx].max_west, lon))));

		if (x >= 0 && x <= mpi && y >= 0 && y <= mpi) {
			dem[indx].mask[x][y] |= value;
			return static_cast<int>(dem[indx].mask[x][y]);
		}
	}

	return -1;
}

auto GetMask(double lat, double lon) -> int
{
	/* This function returns the mask bits based on the latitude
	   and longitude given. */

	return (OrMask(lat, lon, 0));
}

void PutSignal(double lat, double lon, unsigned char signal)
{
	/* This function writes a signal level (0-255)
	   at the specified location for later recall. */

	hottest = std::max<int>(signal, hottest);	// dBm, dBuV

	//lookup x/y for this co-ord
	for (int indx = 0; indx < MAXPAGES; ++indx) {
		const int x = static_cast<int>(std::rint(ppd * (lat - dem[indx].min_north)));
		const int y = mpi - static_cast<int>(std::rint(yppd * (LonDiff(dem[indx].max_west, lon))));

		if (x >= 0 && x <= mpi && y >= 0 && y <= mpi) {
			dem[indx].signal[x][y] = signal;
			// return (dem[indx].signal[x][y]);
			return;
		}
	}

	// return 0;
}

auto GetSignal(double lat, double lon) -> unsigned char
{
	/* This function reads the signal level (0-255) at the
	   specified location that was previously written by the
	   complimentary PutSignal() function. */

	for (int indx = 0; indx < MAXPAGES; ++indx) {
		const int x = static_cast<int>(std::rint(ppd * (lat - dem[indx].min_north)));
		const int y = mpi - static_cast<int>(std::rint(yppd * (LonDiff(dem[indx].max_west, lon))));

		if (x >= 0 && x <= mpi && y >= 0 && y <= mpi) {
			return (dem[indx].signal[x][y]);
		}
	}

	return 0;
}

auto GetElevation(const struct site_t& location) -> double
{
	/* This function returns the elevation (in feet) of any location
	   represented by the digital elevation model data in memory.
	   Function returns -5000.0 for locations not found in memory. */

	for (int indx = 0; indx < MAXPAGES; ++indx) {
		const int x = static_cast<int>(std::rint(ppd * (location.lat - dem[indx].min_north)));
		const int y = mpi - static_cast<int>(std::rint(yppd * (LonDiff(dem[indx].max_west, location.lon))));

		if (x >= 0 && x <= mpi && y >= 0 && y <= mpi) {
			return 3.28084 * dem[indx].data[x][y];
		}
	}

	return -5000.0;
}

auto AddElevation(double lat, double lon, double height, int size) -> int
{
	/* This function adds a user-defined terrain feature
	   (in meters AGL) to the digital elevation model data
	   in memory.  Does nothing and returns 0 for locations
	   not found in memory. */

	for (int indx = 0; indx < MAXPAGES; ++indx) {
		const int x = static_cast<int>(std::rint(ppd * (lat - dem[indx].min_north)));
		const int y = mpi - static_cast<int>(std::rint(yppd * (LonDiff(dem[indx].max_west, lon))));

		if (x >= 0 && x <= mpi && y >= 0 && y <= mpi) {
			if (size<2) {
				dem[indx].data[x][y] += static_cast<short>(std::rint(height));
			}

			// Make surrounding area bigger for wide area landcover. Should enhance 3x3 pixels including c.p
			if (size>1){
				for(int i=size*-1; i <= size; i=i+1){
					for(int j=size*-1; j <= size; j=j+1){
						if(x+j >= 0 && x+j <=IPPD && y+i >= 0 && y+i <=IPPD) {
							dem[indx].data[x+j][y+i] += static_cast<short>(std::rint(height));
						}
					}
				}
			}
			return 1;
		}
	}

	return 0;
}

auto ElevationAngle(const struct site_t& source, const struct site_t& destination) -> double
{
	/* This function returns the angle of elevation (in degrees)
	   of the destination as seen from the source location.
	   A positive result represents an angle of elevation (uptilt),
	   while a negative result represents an angle of depression
	   (downtilt), as referenced to a normal to the center of
	   the earth. */

	const double a = GetElevation(destination) + destination.alt + earthradius;
	const double b = GetElevation(source) + source.alt + earthradius;

	const double dx = FEET_PER_MILE * Distance(source, destination);

	/* Apply the Law of Cosines */

	return ((180.0 *
		 (std::acos(((b * b) + (dx * dx) - (a * a)) / (2.0 * b * dx))) * std::numbers::inv_pi) - 90.0);
}

auto ReadPath(const struct site_t& source, const struct site_t& destination) -> struct path_t
{
	/* This function generates a sequence of latitude and
	   longitude positions between source and destination
	   locations along a great circle path, and stores
	   elevation and distance information for points
	   along that path in the "path" structure. */

	int c = 0;
	double beta = 0.0;
	double miles_per_sample = 0.0;
	struct site_t tempsite;

	double lat1 = source.lat * DEG2RAD;
	double lon1 = source.lon * DEG2RAD;
	double lat2 = destination.lat * DEG2RAD;
	double lon2 = destination.lon * DEG2RAD;
	const double samples_per_radian = ppd * 57.295833;
	const double azimuth = Azimuth(source, destination) * DEG2RAD;

	double total_distance = Distance(source, destination);

	struct path_t path;
	path.lat.resize(ARRAYSIZE);
	path.lon.resize(ARRAYSIZE);
	path.elevation.resize(ARRAYSIZE);
	path.distance.resize(ARRAYSIZE);

	if (total_distance > (30.0 / ppd)) {
		const double dx = samples_per_radian * std::acos(std::cos(lon1 - lon2));
		const double dy = samples_per_radian * std::acos(std::cos(lat1 - lat2));
		const double path_length = std::hypot(dx, dy);
		miles_per_sample = total_distance / path_length;
	}

	else {
		c = 0;
		total_distance = 0.0;

		lat1 = lat1 / DEG2RAD;
		lon1 = lon1 / DEG2RAD;

		path.lat[c] = lat1;
		path.lon[c] = lon1;
		path.elevation[c] = GetElevation(source);
		path.distance[c] = 0.0;
	}

	double distance = 0.0;
	for (c = 0; (total_distance != 0.0 && distance <= total_distance && c < ARRAYSIZE); c++) {
		beta = distance / 3959.0;
		auto sin_lat1 = std::sin(lat1);
		auto cos_lat1 = std::cos(lat1);
		auto cos_beta = std::cos(beta);
		lat2 =
		    std::asin(sin_lat1 * cos_beta + std::cos(azimuth) * std::sin(beta) * cos_lat1);
		const double num = cos_beta - (sin_lat1 * std::sin(lat2));
		const double den = cos_lat1 * std::cos(lat2);

		if ((azimuth == 0.0 && (beta > HALFPI - lat1)) || (azimuth == HALFPI && (beta > HALFPI + lat1))) {
			lon2 = lon1 + std::numbers::pi;
		}

		else if (std::fabs(num / den) > 1.0) {
			lon2 = lon1;
		}

		else {
			if ((std::numbers::pi - azimuth) >= 0.0) {
				lon2 = lon1 - arccos(num, den);
			}
			else {
				lon2 = lon1 + arccos(num, den);
			}
		}

		while (lon2 < 0.0) {
			lon2 += TWOPI;
		}

		while (lon2 > TWOPI) {
			lon2 -= TWOPI;
		}

		lat2 = lat2 / DEG2RAD;
		lon2 = lon2 / DEG2RAD;

		path.lat[c] = lat2;
		path.lon[c] = lon2;
		tempsite.lat = lat2;
		tempsite.lon = lon2;
		path.elevation[c] = GetElevation(tempsite);
		// fix for tile gaps in multi-tile LIDAR plots
		if(path.elevation[c]==0 && path.elevation[c-1] > 10) {
			path.elevation[c]=path.elevation[c-1];
		}
		path.distance[c] = distance;
		distance = miles_per_sample * (c + 1);
	}

	/* Make sure exact destination point is recorded at path.length-1 */

	if (c < ARRAYSIZE) {
		path.lat[c] = destination.lat;
		path.lon[c] = destination.lon;
		path.elevation[c] = GetElevation(destination);
		path.distance[c] = total_distance;
		c++;
	}

	if (c < ARRAYSIZE) {
		path.length = c;
	}
	else {
		path.length = ARRAYSIZE - 1;
	}
	return path;
}

auto ElevationAngle2(const struct site_t& source, const struct site_t& destination, double er) -> double
{
	/* This function returns the angle of elevation (in degrees)
	   of the destination as seen from the source location, UNLESS
	   the path between the sites is obstructed, in which case, the
	   elevation angle to the first obstruction is returned instead.
	   "er" represents the earth radius. */

	auto path = ReadPath(source, destination);

	double distance = FEET_PER_MILE * Distance(source, destination);
	const double source_alt = er + source.alt + GetElevation(source);
	const double destination_alt = er + destination.alt + GetElevation(destination);
	const double source_alt2 = source_alt * source_alt;

	/* Calculate the cosine of the elevation angle of the
	   destination (receiver) as seen by the source (transmitter). */

	const double cos_xmtr_angle =
	    ((source_alt2) + (distance * distance) -
	     (destination_alt * destination_alt)) / (2.0 * source_alt *
						     distance);

	/* Test all points in between source and destination locations to
	   see if the angle to a topographic feature generates a higher
	   elevation angle than that produced by the destination.  Begin
	   at the source since we're interested in identifying the FIRST
	   obstruction along the path between source and destination. */

	for (int x = 2; x < path.length; x++) {
		distance = FEET_PER_MILE * path.distance[x];

		auto test_alt =
		    earthradius + (path.elevation[x] ==
				   0.0 ? path.elevation[x] : path.elevation[x] + clutter);

		const double cos_test_angle =
		    ((source_alt2) + (distance * distance) -
		     (test_alt * test_alt)) / (2.0 * source_alt * distance);

		/* Compare these two angles to determine if
		   an obstruction exists.  Since we're comparing
		   the cosines of these angles rather than
		   the angles themselves, the sense of the
		   following "if" statement is reversed from
		   what it would be if the angles themselves
		   were compared. */

		if (cos_xmtr_angle >= cos_test_angle) {
			return (std::acos(cos_test_angle) / DEG2RAD) - 90.0;
		}
	}

	return (std::acos(cos_xmtr_angle) / DEG2RAD) - 90.0;
}

auto ReadBearing(std::string_view input) -> double
{
	/* This function takes numeric input in the form of a character
	   string, and returns an equivalent bearing in degrees as a
	   decimal number (double).  The input may either be expressed
	   in decimal format (40.139722) or degree, minute, second
	   format (40 08 23).  This function also safely handles
	   extra spaces found either leading, trailing, or
	   embedded within the numbers expressed in the
	   input string.  Decimal seconds are permitted. */

	double bearing = 0.0;
	std::string outstr;

	/* Copy "input" to "string", and ignore any extra
	   spaces that might be present in the process. */
	auto length = input.length();

	for (int a = 0; a < length && a < 18; a++) {
		if ((input[a] != 32 && input[a] != '\n') || (input[a] == 32 && input[a + 1] != 32 && input[a + 1] != '\n' && !outstr.empty())) {
			outstr += input[a];
		}
	}

	/* Count number of spaces in the clean string. */
	auto num_spaces = std::ranges::count(outstr, 32);

	if (num_spaces == 0) {		/* Decimal Format (40.139722) */
		std::from_chars(outstr.data(), outstr.data() + outstr.size(), bearing);
	}

	else if (num_spaces == 2) {		/* Degree, Minute, Second Format (40 08 23.xx) */
		int degrees = 0;
		int minutes = 0;
		double seconds = 0.0;
		sscanf(outstr.data(), "%d %d %lf", &degrees, &minutes, &seconds);

		bearing = std::fabs(static_cast<double>(degrees));
		bearing += std::fabs(static_cast<double>(minutes) / 60.0);
		bearing += std::fabs(seconds / 3600.0);

		if ((degrees < 0) || (minutes < 0) || (seconds < 0.0)) {
			bearing = -bearing;
		}
	}

	/* Anything else returns a 0.0 */
	if (bearing > 360.0 || bearing < -360.0) {
		bearing = 0.0;
	}

	return bearing;
}

void ObstructionAnalysis(struct site_t xmtr, struct site_t rcvr, double f, std::ofstream& outfile)
{
	/* Perform an obstruction analysis along the
	   path between receiver and transmitter. */

	struct site_t site_x;
	double cos_test_angle = 0.0;
	double h_f = 0.0;
	double h_los = 0.0;
	double lambda = 0.0;
	std::string string_fpt6;
	std::string string_f1;
	std::string outstr;

	auto path = ReadPath(xmtr, rcvr);
	double h_r = GetElevation(rcvr) + rcvr.alt + earthradius;
	double h_r_f1 = h_r;
	double h_r_fpt6 = h_r;
	const double h_r_orig = h_r;
	const double h_t = GetElevation(xmtr) + xmtr.alt + earthradius;
	const double d_tx = FEET_PER_MILE * Distance(rcvr, xmtr);
	double cos_tx_angle =
	    ((h_r * h_r) + (d_tx * d_tx) - (h_t * h_t)) / (2.0 * h_r * d_tx);

	if (f != 0.0) {
		lambda = 9.8425e8 / (f * 1e6);
	}

	if (clutter > 0.0) {
		std::print(outfile, "Terrain has been raised by");

		if (metric) {
			std::print(outfile, " {:.2f} meters", METERS_PER_FOOT * clutter);
		}
		else {
			std::print(outfile, " {:.2f} feet", clutter);
		}

		std::println(outfile, " to account for ground clutter.\n");
	}

	/* At each point along the path calculate the cosine
	   of a sort of "inverse elevation angle" at the receiver.
	   From the antenna, 0 deg. looks at the ground, and 90 deg.
	   is parallel to the ground.

	   Start at the receiver.  If this is the lowest antenna,
	   then terrain obstructions will be nearest to it.  (Plus,
	   that's the way ppa!'s original los() did it.)

	   Calculate cosines only.  That's sufficient to compare
	   angles and it saves the extra computational burden of
	   acos().  However, note the inverted comparison: if
	   acos(A) > acos(B), then B > A. */

	for (int x = path.length - 1; x > 0; x--) {
		site_x.lat = path.lat[x];
		site_x.lon = path.lon[x];
		site_x.alt = 0.0;

		const double h_x = GetElevation(site_x) + earthradius + clutter;
		const double d_x = FEET_PER_MILE * Distance(rcvr, site_x);

		/* Deal with the LOS path first. */

		cos_test_angle =
		    ((h_r * h_r) + (d_x * d_x) -
		     (h_x * h_x)) / (2.0 * h_r * d_x);

		if (cos_tx_angle > cos_test_angle) {
			if (h_r == h_r_orig) {
				std::println(outfile,
					"Between {} and {}, obstructions were detected at:\n",
					rcvr.name, xmtr.name);
			}

			if (site_x.lat >= 0.0) {
				if (metric) {
					std::println(outfile,
						"   {:8.4f} N,{:9.4f} W, {:5.2f} kilometers, {:6.2f} meters AMSL",
						site_x.lat, site_x.lon,
						KM_PER_MILE * (d_x / FEET_PER_MILE),
						METERS_PER_FOOT * (h_x - earthradius));
				}
				else {
					std::println(outfile,
						"   {:8.4f} N,{:9.4f} W, {:5.2f} miles, {:6.2f} feet AMSL",
						site_x.lat, site_x.lon,
						d_x / FEET_PER_MILE,
						h_x - earthradius);
				}
			}

			else {
				if (metric) {
					std::println(outfile,
						"   {:8.4f} S,{:9.4f} W, {:5.2f} kilometers, {:6.2f} meters AMSL",
						-site_x.lat, site_x.lon,
						KM_PER_MILE * (d_x / FEET_PER_MILE),
						METERS_PER_FOOT * (h_x - earthradius));
				}
				else {
					std::println(outfile,
						"   {:8.4f} S,{:9.4f} W, {:5.2f} miles, {:6.2f} feet AMSL",
						-site_x.lat, site_x.lon,
						d_x / FEET_PER_MILE,
						h_x - earthradius);
				}
			}
		}

		while (cos_tx_angle > cos_test_angle) {
			h_r += 1;
			cos_test_angle =
			    ((h_r * h_r) + (d_x * d_x) -
			     (h_x * h_x)) / (2.0 * h_r * d_x);
			cos_tx_angle =
			    ((h_r * h_r) + (d_tx * d_tx) -
			     (h_t * h_t)) / (2.0 * h_r * d_tx);
		}

		if (f != 0.0) {
			/* Now clear the first Fresnel zone... */

			double cos_tx_angle_f1 =
			    ((h_r_f1 * h_r_f1) + (d_tx * d_tx) -
			     (h_t * h_t)) / (2.0 * h_r_f1 * d_tx);
			h_los =
			    std::sqrt(h_r_f1 * h_r_f1 + d_x * d_x -
				 2 * h_r_f1 * d_x * cos_tx_angle_f1);
			h_f = h_los - std::sqrt(lambda * d_x * (d_tx - d_x) / d_tx);

			while (h_f < h_x) {
				h_r_f1 += 1;
				cos_tx_angle_f1 =
				    ((h_r_f1 * h_r_f1) + (d_tx * d_tx) -
				     (h_t * h_t)) / (2.0 * h_r_f1 * d_tx);
				h_los =
				    std::sqrt(h_r_f1 * h_r_f1 + d_x * d_x -
					 2 * h_r_f1 * d_x * cos_tx_angle_f1);
				h_f =
				    h_los -
				    std::sqrt(lambda * d_x * (d_tx - d_x) / d_tx);
			}

			/* and clear the 60% F1 zone. */

			double cos_tx_angle_fpt6 =
			    ((h_r_fpt6 * h_r_fpt6) + (d_tx * d_tx) -
			     (h_t * h_t)) / (2.0 * h_r_fpt6 * d_tx);
			h_los =
			    std::sqrt(h_r_fpt6 * h_r_fpt6 + d_x * d_x -
				 2 * h_r_fpt6 * d_x * cos_tx_angle_fpt6);
			h_f = h_los - fzone_clearance * std::sqrt(lambda * d_x * (d_tx - d_x) / d_tx);

			while (h_f < h_x) {
				h_r_fpt6 += 1;
				cos_tx_angle_fpt6 =
				    ((h_r_fpt6 * h_r_fpt6) + (d_tx * d_tx) -
				     (h_t * h_t)) / (2.0 * h_r_fpt6 * d_tx);
				h_los =
				    std::sqrt(h_r_fpt6 * h_r_fpt6 + d_x * d_x -
					 2 * h_r_fpt6 * d_x *
					 cos_tx_angle_fpt6);
				h_f =
				    h_los -
				    fzone_clearance * std::sqrt(lambda * d_x *
							   (d_tx - d_x) / d_tx);
			}
		}
	}

	if (h_r > h_r_orig) {
		if (metric) {
			outstr = std::format(
				 "\nAntenna at {} must be raised to at least {:.2f} meters AGL\nto clear all obstructions detected.\n",
				 rcvr.name,
				 METERS_PER_FOOT * (h_r - GetElevation(rcvr) - earthradius));
		}
		else {
			outstr = std::format(
				 "\nAntenna at {} must be raised to at least {:.2f} feet AGL\nto clear all obstructions detected.\n",
				 rcvr.name,
				 h_r - GetElevation(rcvr) - earthradius);
		}
	}

	else {
		outstr = "\nNo obstructions to LOS path due to terrain were detected\n";
	}

	if (f) {
		if (h_r_fpt6 > h_r_orig) {
			if (metric) {
				string_fpt6 = std::format(
					 "\nAntenna at {} must be raised to at least {:.2f} meters AGL\nto clear {:.0f}{} of the first Fresnel zone.\n",
					 rcvr.name,
					 METERS_PER_FOOT * (h_r_fpt6 - GetElevation(rcvr) - earthradius),
					 fzone_clearance * 100.0, static_cast<char>(37));
			}
			else {
				string_fpt6 = std::format(
					 "\nAntenna at {} must be raised to at least {:.2f} feet AGL\nto clear {:.0f}{} of the first Fresnel zone.\n",
					 rcvr.name,
					 h_r_fpt6 - GetElevation(rcvr) - earthradius, fzone_clearance * 100.0,
					 static_cast<char>(37));
			}
		}
		else {
			string_fpt6 = std::format(
				 "\n{:.0f}{} of the first Fresnel zone is clear.\n",
				 fzone_clearance * 100.0, static_cast<char>(37));
		}

		if (h_r_f1 > h_r_orig) {
			if (metric) {
				string_f1 = std::format(
					 "\nAntenna at {} must be raised to at least {:.2f} meters AGL\nto clear the first Fresnel zone.\n",
					 rcvr.name,
					 METERS_PER_FOOT * (h_r_f1 - GetElevation(rcvr) - earthradius));
			}
			else {
				string_f1 = std::format(
					 "\nAntenna at {} must be raised to at least {:.2f} feet AGL\nto clear the first Fresnel zone.\n",
					 rcvr.name,
					 h_r_f1 - GetElevation(rcvr) - earthradius);
			}
		}
		else {
			string_f1 = "\nThe first Fresnel zone is clear.\n";
		}
	}

	std::print(outfile, "{}", outstr);

	if (f != 0.0) {
		std::print(outfile, "{}", string_f1);
		std::print(outfile, "{}", string_fpt6);
	}

}

void free_dem()
{
	for (int i = 0; i < MAXPAGES; i++) {
		for (int j = 0; j < IPPD; j++) {
			delete [] dem[i].data[j];
			delete [] dem[i].mask[j];
			delete [] dem[i].signal[j];
		}
		delete [] dem[i].data;
		delete [] dem[i].mask;
		delete [] dem[i].signal;
	}
	delete [] dem;
}

//void free_elev() {
//  delete [] elev;
//}

//void free_path(void)
//{
//	delete [] path.lat;
//	delete [] path.lon;
//	delete [] path.elevation;
//	delete [] path.distance;
//}

//void alloc_elev()
//{
//  elev  = new double[ARRAYSIZE + 10];
//}

void alloc_dem()
{
	dem = new struct dem_t[MAXPAGES];
	for (int i = 0; i < MAXPAGES; i++) {
		dem[i].data = new short *[IPPD];
		dem[i].mask = new unsigned char *[IPPD];
		dem[i].signal = new unsigned char *[IPPD];
		for (int j = 0; j < IPPD; j++) {
			dem[i].data[j] = new short[IPPD];
			dem[i].mask[j] = new unsigned char[IPPD];
			dem[i].signal[j] = new unsigned char[IPPD];
		}
	}
}

//void alloc_path()
//{
//	path.lat = new double[ARRAYSIZE];
//	path.lon = new double[ARRAYSIZE];
//	path.elevation = new double[ARRAYSIZE];
//	path.distance = new double[ARRAYSIZE];
//}

void do_allocs()
{

	//alloc_elev();
	alloc_dem();
	//alloc_path();

	for (int i = 0; i < MAXPAGES; i++) {
		dem[i].min_el = 32768;
		dem[i].max_el = -32768;
		dem[i].min_north = 90;
		dem[i].max_north = -90;
		dem[i].min_west = 360;
		dem[i].max_west = -1;
	}
}

auto main(int argc, char *argv[]) -> int
{
	int x = 0;
	int z = 0;
	int propmodel = 0;
	int knifeedge = 0;
	int ppa = 0;
	bool normalise = false;
	int haf = 0;
	int pmenv = 1;
	bool lidar=false;
	int result = 0;

	bool use_threads = true;
	bool to_stdout = false;
	bool cropping = true;

	unsigned char LRmap = 0;
	bool txsites = false;
	bool geo = false;
	bool kml = false;
	unsigned char area_mode = 0;
	unsigned char max_txsites = 0;
	bool ngs = false;

	// TODO: convert string filenames to std::filesystem
	std::string mapfile;
	std::string ano_filename;
	std::string lidar_tiles;
	lidar_tiles.resize(27000);
	std::string clutter_file;
	std::string antenna_file;
	std::string az_filename;
	std::string el_filename;
	char *udt_file = nullptr;

	double altitude = 0.0;
	double altitudeLR = 0.0;
	double tx_range = 0.0;
	double rx_range = 0.0;
	double deg_range = 0.0;
	double deg_limit = 0.0;
	double deg_range_lon = 0.0;

	if (strstr(argv[0], "signalserverHD")) {
		MAXPAGES = 32;  // was 9
		ARRAYSIZE = 115210;  // was 32410
		IPPD = 3600;
	}

	if (strstr(argv[0], "signalserverLIDAR")) {
		MAXPAGES = 100; // 10x10
		lidar = true;
		IPPD = 6000; // will be overridden based upon file header...
	}

	std::string ss_name = "Signal Server";

	if (argc == 1) {
		std::println(stdout, "Version: {} {:.2f} (Built for {} DEM tiles at {} pixels)", ss_name, version,MAXPAGES, IPPD);
		std::println(stdout, "License: GNU General Public License (GPL) version 2\n");
		std::println(stdout, "Radio propagation simulator by Alex Farrant QCVS, 2E0TDW");
		std::println(stdout, "Based upon SPLAT! by John Magliacane, KD2BD");
		std::println(stdout, "Some feature enhancements/additions by Aaron A. Collins, N9OZB\n");
		std::println(stdout, "Usage: signalserver [data options] [input options] [antenna options] [output options] -o outputfile\n");
		std::println(stdout, "Data:");
		std::println(stdout, "     -sdf Directory containing SRTM derived .sdf DEM tiles (may be .gz or .bz2)");
		std::println(stdout, "     -lid ASCII grid tile (LIDAR) with dimensions and resolution defined in header");
		std::println(stdout, "     -udt User defined point clutter as decimal co-ordinates: 'latitude,longitude,height'");
		std::println(stdout, "     -clt MODIS 17-class wide area clutter in ASCII grid format");
		std::println(stdout, "     -color File to pre-load .scf/.lcf/.dcf for Signal/Loss/dBm color palette");
		std::println(stdout, "Input:");
		std::println(stdout,	"     -lat Tx Latitude (decimal degrees) -70/+70");
		std::println(stdout,	"     -lon Tx Longitude (decimal degrees) -180/+180");
		std::println(stdout,	"     -rla (Optional) Rx Latitude for PPA (decimal degrees) -70/+70");
		std::println(stdout, "     -rlo (Optional) Rx Longitude for PPA (decimal degrees) -180/+180");
		std::println(stdout,	"     -f Tx Frequency (MHz) 20MHz to 100GHz (LOS after 20GHz)");
		std::println(stdout,	"     -erp Tx Total Effective Radiated Power in Watts (dBd) inc Tx+Rx gain. 2.14dBi = 0dBd");
		std::println(stdout, "     -gc Random ground clutter (feet/meters)");
		std::println(stdout, "     -m Metric units of measurement");
		std::println(stdout, "     -te Terrain code 1-6 (optional - 1. Water, 2. Marsh, 3. Farmland,");
		std::println(stdout, "          4. Mountain, 5. Desert, 6. Urban");
		std::println(stdout,	"     -terdic Terrain dielectric value 2-80 (optional)");
		std::println(stdout,	"     -tercon Terrain conductivity 0.01-0.0001 (optional)");
		std::println(stdout, "     -cl Climate code 1-7 (optional - 1. Equatorial 2. Continental subtropical");
		std::println(stdout,	"          3. Maritime subtropical 4. Desert 5. Continental temperate");
		std::println(stdout,	"          6. Maritime temperate (Land) 7. Maritime temperate (Sea)");
		std::println(stdout, "     -rel Reliability for ITM model (% of 'time') 1 to 99 (optional, default 50%)");
		std::println(stdout, "     -conf Confidence for ITM model (% of 'situations') 1 to 99 (optional, default 50%)");
		std::println(stdout, "     -resample Reduce Lidar resolution by specified factor (2 = 50%)");
		std::println(stdout, "Output:");
		std::println(stdout, "     -o basename (Output file basename - required)");
		std::println(stdout,	"     -dbm Plot Rxd signal power instead of field strength in dBuV/m");
		std::println(stdout, "     -rt Rx Threshold (dB / dBm / dBuV/m)");
		std::println(stdout, "     -R Radius (miles/kilometers)");
		std::println(stdout,	"     -res Pixels per tile. 300/600/1200/3600 (Optional. LIDAR res is within the tile)");
		std::println(stdout,	"     -pm Propagation model. 1: ITM, 2: LOS, 3: Hata, 4: ECC33,");
		std::println(stdout,	"          5: SUI, 6: COST-Hata, 7: FSPL, 8: ITWOM, 9: Ericsson,");
		std::println(stdout, "          10: Plane earth, 11: Egli VHF/UHF, 12: Soil");
		std::println(stdout,	"     -pe Propagation model mode: 1=Urban,2=Suburban,3=Rural");
		std::println(stdout,	"     -ked Knife edge diffraction (Already on for ITM)");
		std::println(stdout, "Antenna:");
		std::println(stdout, "     -ant (antenna pattern file basename+path for .az and .el files)");
		std::println(stdout, "     -txh Tx Height (above ground)");
		std::println(stdout,	"     -rxh Rx Height(s) (optional. Default=0.1)");
		std::println(stdout,	"     -rxg Rx gain dBd (optional for PPA text report)");
		std::println(stdout,	"     -hp Horizontal Polarisation (default=vertical)");
		std::println(stdout, "     -rot  (  0.0 - 359.0 degrees, default 0.0) Antenna Pattern Rotation");
		std::println(stdout, "     -dt   ( -10.0 - 90.0 degrees, default 0.0) Antenna Downtilt");
		std::println(stdout, "     -dtdir ( 0.0 - 359.0 degrees, default 0.0) Antenna Downtilt Direction");
		std::println(stdout, "Debugging:");
		std::println(stdout, "     -t Terrain greyscale background");
		std::println(stdout, "     -dbg Verbose debug messages");
		std::println(stdout, "     -ng Normalise Path Profile graph");
		std::println(stdout, "     -haf Halve 1 or 2 (optional)");
		std::println(stdout, "     -nothreads Turn off threaded processing");

		return 1;
	}

	/*
	 * If we're not called as signalserverLIDAR we can allocate various
	 * memory now. For LIDAR we need to wait until we've parsed
	 * the headers in the .asc file to know how much memory to allocate...
	 */
	if (! lidar) {
		do_allocs();
	}

	int y = argc - 1;
	geo = false;
	dbm = false;
	metric = false;
	mapfile[0] = 0;
	clutter_file[0] = 0;
	clutter = 0.0;
	sdf_path[0] = 0;
	udt_file = nullptr;
	max_txsites = 30;
	fzone_clearance = 0.6;
	contour_threshold = 0;
	resample = 0;

	ano_filename[0] = 0;
	earthradius = EARTHRADIUS_FT;
	max_range = 1.0;
	propmodel = 1;		//ITM
	ngs = true;		// no terrain background
	kml = true;
	LRmap = 1;
	area_mode = 1;
	ippd = IPPD;		// default resolution

	altitudeLR = 0.1;

	// Defaults
	LR.eps_dielect = 15.0;	// Farmland
	LR.sgm_conductivity = 0.005;	// Farmland
	LR.eno_ns_surfref = 301.0;
	LR.frq_mhz = 19.0;	// Deliberately too low
	LR.radio_climate = 5;	// continental
	LR.pol = 1;		// vert
	LR.conf = 0.50;
	LR.rel = 0.50;
	LR.erp = 0.0;		// will default to Path Loss

	antenna_rotation = -1;  // unique defaults to test usage
	antenna_downtilt = 99.0; // don't mess with them!
	antenna_dt_direction = -1;
	antenna_file = "";

	tx_site[0].lat = 91.0;
	tx_site[0].lon = 361.0;
	tx_site[1].lat = 91.0;
	tx_site[1].lon = 361.0;

	/* Scan for command line arguments */

	for (x = 1; x <= y; x++) {

		if (strcmp(argv[x], "-R") == 0) {
			z = x + 1;

			if (z <= y && argv[z][0] && argv[z][0] != '-') {
				sscanf(argv[z], "%lf", &max_range);

			}
		}

		if (strcmp(argv[x], "-gc") == 0) {
			z = x + 1;

			if (z <= y && argv[z][0] && argv[z][0] != '-') {
				sscanf(argv[z], "%lf", &clutter);

				clutter = std::max(0.0, clutter);
			}
		}

		if (strcmp(argv[x], "-clt") == 0) {
			z = x + 1;

			if (z <= y && argv[z][0] && argv[z][0] != '-') {
				clutter_file = argv[z];
			}
		}

		if (strcmp(argv[x], "-ant") == 0) {
			z = x + 1;

			if (z <= y && argv[z][0] && argv[z][0] != '-') {
				antenna_file = argv[z];
				std::println("Using antenna_file: {}", antenna_file);
			}
		}

		if (strcmp(argv[x], "-rot") == 0) {
			z = x + 1;

			if (z <= y && argv[z][0] && argv[z][0] != '-') {
				sscanf(argv[z], "%lf", &antenna_rotation);

				antenna_rotation = std::clamp(antenna_rotation, 0.0, 359.0);
			}
		}

		if (strcmp(argv[x], "-dt") == 0) {
			z = x + 1;

			if (z <= y && argv[z][0]) {	/* A minus argument is legal here */
				sscanf(argv[z], "%lf", &antenna_downtilt);

				antenna_downtilt = std::clamp(antenna_downtilt, -10.0, 90.0);
			}
		}

		if (strcmp(argv[x], "-dtdir") == 0) {
			z = x + 1;

			if (z <= y && argv[z][0] && argv[z][0] != '-') {
				sscanf(argv[z], "%lf", &antenna_dt_direction);

				antenna_dt_direction = std::clamp(antenna_dt_direction, 0.0, 359.0);
			}
		}

		if (strcmp(argv[x], "-o") == 0) {
			z = x + 1;

			if (z <= y && argv[z][0] && argv[z][0] != '-') {
				mapfile = argv[z];
				strncpy(tx_site[0].name, "Tx", 2);
				tx_site[0].filename = argv[z];
				/* Antenna pattern files have the same basic name as the output file
				 * but with a different extension. If they exist, load them now */
				az_filename.reserve(strlen(argv[z]) + strlen(Input::AZ_FILE_SUFFIX) + 1);
				if (!antenna_file.empty()) {
				        az_filename = antenna_file;
				}
				else {
				        az_filename = argv[z];
				}
				az_filename += Input::AZ_FILE_SUFFIX;

				el_filename.reserve(strlen(argv[z]) + strlen(Input::EL_FILE_SUFFIX) + 1);
				if (!antenna_file.empty()) {
				        el_filename = antenna_file;
				}
				else {
				        el_filename = argv[z];
				}
				el_filename += Input::EL_FILE_SUFFIX;

				if(result = Input::LoadPAT(az_filename,el_filename); result != 0 ){
					std::println(stderr,"Permissions error reading antenna pattern file");
					exit(result);
				}
				az_filename.clear();
				el_filename.clear();
			} else if (z <= y && argv[z][0] && argv[z][0] == '-' && argv[z][1] == '\0' ) {
				/* Handle writing image data to stdout */
				to_stdout = true;
				mapfile[0] = '\0';
				strncpy(tx_site[0].name, "Tx", 2);
				tx_site[0].filename[0] = '\0';
				std::println(stderr,"Writing to stdout");
			}
		}

		if (strcmp(argv[x], "-rt") == 0) {
			z = x + 1;

			if (z <= y && argv[z][0])	/* A minus argument is legal here */
				sscanf(argv[z], "%d", &contour_threshold);
		}

		if (strcmp(argv[x], "-m") == 0) {
			metric = true;
		}

		if (strcmp(argv[x], "-t") == 0) {
			ngs = false;	// greyscale background
		}

		if (strcmp(argv[x], "-dbm") == 0) {
			dbm = true;
		}

		if (strcmp(argv[x], "-sdf") == 0) {
			z = x + 1;

			if (z <= y && argv[z][0] && argv[z][0] != '-') {
				sdf_path = argv[z];
			}
		}
		
		if (strcmp(argv[x], "-lid") == 0) {
			z = x + 1;
			lidar=1;
			if (z <= y && argv[z][0] && argv[z][0] != '-') {
				lidar_tiles = argv[z];
			}
		}

		if (strcmp(argv[x], "-res") == 0) {
			z = x + 1;

			if (!lidar && z <= y && argv[z][0] && argv[z][0] != '-') {
				sscanf(argv[z], "%d", &ippd);

				switch (ippd) {
				case 300:
					MAXRAD = 500;
					Input::jgets = 3; // 3 dummy reads
					break;
				case 600:
					MAXRAD = 500;
					Input::jgets = 1;
					break;
				case 1200:
					MAXRAD = 200;
					ippd = 1200;
					break;
				case 3600:
					MAXRAD = 100;
					ippd = 3600;
					break;
				default:
					MAXRAD = 200;
					ippd = 1200;
					break;
				}
			}
		}

		if (strcmp(argv[x], "-resample") == 0) {
			z = x + 1;

			if(!lidar){
				std::println(stderr, "Error, this should only be used with LIDAR tiles.");
				return -1;
			}

			sscanf(argv[z], "%d", &resample);
		}

		if (strcmp(argv[x], "-lat") == 0) {
			z = x + 1;

			if (z <= y && argv[z][0]) {
				tx_site[0].lat = ReadBearing(argv[z]);
			}
		}
		if (strcmp(argv[x], "-lon") == 0) {
			z = x + 1;
			if (z <= y && argv[z][0]) {
				tx_site[0].lon = ReadBearing(argv[z]);
				tx_site[0].lon *= -1;
				if (tx_site[0].lon < 0.0) {
					tx_site[0].lon += 360.0;
				}
			}
		}
		//Switch to Path Profile Mode if Rx co-ords specified
		if (strcmp(argv[x], "-rla") == 0) {
			z = x + 1;

			if (z <= y && argv[z][0]) {
				ppa = 1;
				tx_site[1].lat = ReadBearing(argv[z]);

			}
		}
		if (strcmp(argv[x], "-rlo") == 0) {
			z = x + 1;
			if (z <= y && argv[z][0]) {
				tx_site[1].lon = ReadBearing(argv[z]);
				tx_site[1].lon *= -1;
				if (tx_site[1].lon < 0.0) {
					tx_site[1].lon += 360.0;
				}
			}
		}

		if (strcmp(argv[x], "-txh") == 0) {
			z = x + 1;

			if (z <= y && argv[z][0] && argv[z][0] != '-') {
				sscanf(argv[z], "%f", &tx_site[0].alt);

			}
			txsites = true;
		}

		if (strcmp(argv[x], "-rxh") == 0) {
			z = x + 1;

			if (z <= y && argv[z][0] && argv[z][0] != '-') {
				sscanf(argv[z], "%lf", &altitudeLR);
				sscanf(argv[z], "%f", &tx_site[1].alt);
			}
		}

		if (strcmp(argv[x], "-rxg") == 0) {
			z = x + 1;

			if (z <= y && argv[z][0] && argv[z][0] != '-') {
				sscanf(argv[z], "%lf", &rxGain);
			}
		}

		if (strcmp(argv[x], "-f") == 0) {
			z = x + 1;

			if (z <= y && argv[z][0] && argv[z][0] != '-') {
				sscanf(argv[z], "%lf", &LR.frq_mhz);
			}
		}

		if (strcmp(argv[x], "-erp") == 0) {
			z = x + 1;

			if (z <= y && argv[z][0] && argv[z][0] != '-') {
				sscanf(argv[z], "%lf", &LR.erp);
			}
		}

		if (strcmp(argv[x], "-cl") == 0) {
			z = x + 1;

			if (z <= y && argv[z][0] && argv[z][0] != '-') {

				sscanf(argv[z], "%d", &LR.radio_climate);

			}
		}
		if (strcmp(argv[x], "-te") == 0) {
			z = x + 1;

			if (z <= y && argv[z][0] && argv[z][0] != '-') {

				sscanf(argv[z], "%d", &ter);

				switch (ter) {
				case 1:	// Water
					terdic = 80;
					tercon = 0.010;
					break;

				case 2:	// Marsh
					terdic = 12;
					tercon = 0.007;
					break;

				case 3:	// Farmland
					terdic = 15;
					tercon = 0.005;
					break;

				case 4:	//Mountain
					terdic = 13;
					tercon = 0.002;
					break;
				case 5:	//Desert
					terdic = 13;
					tercon = 0.002;
					break;
				case 6:	//Urban
					terdic = 5;
					tercon = 0.001;
					break;
				}
				LR.eps_dielect = terdic;
				LR.sgm_conductivity = tercon;

			}
		}

		if (strcmp(argv[x], "-terdic") == 0) {
			z = x + 1;

			if (z <= y && argv[z][0] && argv[z][0] != '-') {

				sscanf(argv[z], "%lf", &terdic);

				LR.eps_dielect = terdic;

			}
		}

		if (strcmp(argv[x], "-tercon") == 0) {
			z = x + 1;

			if (z <= y && argv[z][0] && argv[z][0] != '-') {

				sscanf(argv[z], "%lf", &tercon);

				LR.sgm_conductivity = tercon;

			}
		}

		if (strcmp(argv[x], "-hp") == 0) {
			// Horizontal polarisation (0)
			LR.pol = 0;
		}

		if (strcmp(argv[x], "-dbg") == 0) {
			debug = true;
		}

	
		 /*UDT*/
		if (strcmp(argv[x], "-udt") == 0) {
			z = x + 1;

			if (z <= y && argv[z][0]) {
				udt_file = (char*) calloc(PATH_MAX+1, sizeof(char));
				if( udt_file == nullptr ) {
					return ENOMEM;
				}
				strncpy(udt_file, argv[z], 253);
			}
		}

		/*Prop model */

		if (strcmp(argv[x], "-pm") == 0) {
			z = x + 1;

			if (z <= y && argv[z][0]) {
				sscanf(argv[z], "%d", &propmodel);
			}
		}
		// Prop model variant eg. urban/suburban
		if (strcmp(argv[x], "-pe") == 0) {
			z = x + 1;

			if (z <= y && argv[z][0]) {
				sscanf(argv[z], "%d", &pmenv);
			}
		}
		//Knife edge diffraction
		if (strcmp(argv[x], "-ked") == 0) {
			z = x + 1;
			knifeedge = 1;
		}

		//Normalise Path Profile chart
		if (strcmp(argv[x], "-ng") == 0) {
			z = x + 1;
			normalise = 1;
		}
		//Halve the problem
		if (strcmp(argv[x], "-haf") == 0) {
			z = x + 1;
			if (z <= y && argv[z][0]) {
				sscanf(argv[z], "%d", &haf);
			}
		}

		//Disable threads
		if (strcmp(argv[x], "-nothreads") == 0) {
			z = x + 1;
			use_threads = false;
		}

		// Reliability % for ITM model
		if (strcmp(argv[x], "-rel") == 0) {
			z = x + 1;

			if (z <= y && argv[z][0]) {
				sscanf(argv[z], "%lf", &LR.rel);
				LR.rel=LR.rel/100;
			}
		}
		// Confidence % for ITM model
		if (strcmp(argv[x], "-conf") == 0) {
			z = x + 1;

			if (z <= y && argv[z][0]) {
				sscanf(argv[z], "%lf", &LR.conf);
				LR.conf=LR.conf/100;
			}
		}
		// LossColors for the -scf, -dcf and -lcf, depending on mode
		if (strcmp(argv[x], "-color") == 0) {
			z = x + 1;

			if (z <= y && argv[z][0]) {
				Input::color_file = argv[z];
			}
		}
	}

	/* ERROR DETECTION */
	if (tx_site[0].lat > 90 || tx_site[0].lat < -90) {
		std::println(stderr,
			"ERROR: Either the lat was missing or out of range!");
		exit(EINVAL);

	}
	if (tx_site[0].lon > 360 || tx_site[0].lon < 0) {
		std::println(stderr,
			"ERROR: Either the lon was missing or out of range!");
		exit(EINVAL);

	}
	if (LR.frq_mhz < 20 || LR.frq_mhz > 100000) {
		std::println(stderr,
			"ERROR: Either the Frequency was missing or out of range!");
		exit(EINVAL);
	}
	if (LR.erp > 500000000) {
		std::println(stderr, "ERROR: Power was out of range!");
		exit(EINVAL);

	}
	if (LR.eps_dielect > 80 || LR.eps_dielect < 0.1) {
		std::println(stderr, "ERROR: Ground Dielectric value out of range!");
		exit(EINVAL);

	}
	if (LR.sgm_conductivity > 0.01 || LR.sgm_conductivity < 0.000001) {
		std::println(stderr, "ERROR: Ground conductivity out of range!");
		exit(EINVAL);

	}

	if (tx_site[0].alt < 0 || tx_site[0].alt > 60000) {
		std::println(stderr,
			"ERROR: Tx altitude above ground was too high: {:f}",
			tx_site[0].alt);
		exit(EINVAL);
	}
	if (altitudeLR < 0 || altitudeLR > 60000) {
		std::println(stderr,
			"ERROR: Rx altitude above ground was too high!");
		exit(EINVAL);
	}

	if(!lidar){
		if (ippd < 300 || ippd > 10000) {
			std::println(stderr, "ERROR: resolution out of range!");
			exit(EINVAL);
		}
	}

	if (contour_threshold < -200 || contour_threshold > 240) {
		std::println(stderr,
			"ERROR: Receiver threshold out of range (-200 / +240)");
		exit(EINVAL);
	}
	if (propmodel > 2 && propmodel < 7 && LR.frq_mhz < 150) {
		std::println(stderr,
			"ERROR: Frequency too low for Propagation model");
		exit(EINVAL);
	}

	if (to_stdout && ppa != 0) {
		std::println(stderr,
			"ERROR: Cannot write to stdout in ppa mode");
		exit(EINVAL);
	}

	if(resample > 10){
		std::println(stderr,
			"ERROR: Cannot resample higher than a factor of 10");
		exit(EINVAL);	
	}
	if (metric) {
		altitudeLR /= METERS_PER_FOOT;	/* 10ft * 0.3 = 3.3m */
		max_range /= KM_PER_MILE;	/* 10 / 1.6 = 7.5 */
		altitude /= METERS_PER_FOOT;
		tx_site[0].alt /= METERS_PER_FOOT;	/* Feet to metres */
		tx_site[1].alt /= METERS_PER_FOOT;	/* Feet to metres */
		clutter /= METERS_PER_FOOT;	/* Feet to metres */
	}

	/* Ensure a trailing '/' is present in sdf_path */

	if (! sdf_path.ends_with('/') && !sdf_path.empty()) {
		sdf_path += '/';
	}

	x = 0;
	y = 0;

	double min_lon = std::floor(tx_site[0].lon);
	double max_lon = std::floor(tx_site[0].lon);

	const double txlat = static_cast<int>(std::floor(tx_site[0].lat));
	const double txlon = static_cast<int>(std::floor(tx_site[0].lon));

	double min_lat = std::min(txlat, 70.0);
	double max_lat = std::max(txlat, -70.0);

	if (LonDiff(txlon, min_lon) < 0.0) {
		min_lon = txlon;
	}

	if (LonDiff(txlon, max_lon) >= 0.0) {
		max_lon = txlon;
	}

	if (ppa == 1) {
		const double rxlat = static_cast<int>(std::floor(tx_site[1].lat));
		const double rxlon = static_cast<int>(std::floor(tx_site[1].lon));

		min_lat = std::min(min_lat, rxlat);

		max_lat = std::max(max_lat, rxlat);

		if (LonDiff(rxlon, min_lon) < 0.0) {
			min_lon = rxlon;
		}

		if (LonDiff(rxlon, max_lon) >= 0.0) {
			max_lon = rxlon;
		}
	}

	/* Load the required tiles */
	if (lidar) {
		if(result = Input::loadLIDAR(lidar_tiles, resample); result != 0 ){
			std::println(stderr, "Couldn't find one or more of the "
				"lidar files. Please ensure their paths are "
				"correct and try again.");
			std::println(stderr, "Error {}: {}", result, strerror(result));
			exit(result);
		}

		ppd=(static_cast<double>(Output::height) / (max_north-min_north));
		yppd=ppd;
		
		if (debug) {
			std::println(stderr,"ppd {:f}, yppd {:f}, {:.4f},{:.4f},{:.4f},{:.4f},{} x {}",ppd,yppd,max_north,min_west,min_north,max_west,Output::width,Output::height);
		}

		if (yppd < ppd/4) {
			std::println(stderr,"yppd is bad! Check longitudes");
			exit(1);
		}

		if (delta > 0) {
			tx_site[0].lon+=delta;
		}

	} else {
		// DEM first
		if(debug) {
			std::println(stderr,"{:.4f},{:.4f},{:.4f},{:.4f},{:.4f},{:.4f}",max_north,min_west,min_north,max_west,max_lon,min_lon);
		}

		//max_lon-=3;

		if(result = Input::LoadTopoData(max_lon, min_lon, max_lat, min_lat); result != 0 ){
			// This only fails on errors loading SDF tiles
			std::println(stderr, "Error loading topo data");
			return result;
		}

		if (area_mode) {
			for (z = 0; z < txsites && z < max_txsites; z++) {
				/* "Ball park" estimates used to load any additional
				   SDF files required to conduct this analysis. */

				tx_range =
					std::sqrt(1.5 *
					 (tx_site[z].alt + GetElevation(tx_site[z])));

				if (LRmap) {
					rx_range = std::sqrt(1.5 * altitudeLR);
				}
				else {
					rx_range = std::sqrt(1.5 * altitude);
				}

				/* deg_range determines the maximum
				   amount of topo data we read */

				deg_range = (tx_range + rx_range) / 57.0;

				/* max_range regulates the size of the
				   analysis.  A small, non-zero amount can
				   be used to shrink the size of the analysis
				   and limit the amount of topo data read by
				   ss  A large number will increase the
				   width of the analysis and the size of
				   the map. */

				if (max_range == 0.0) {
					max_range = tx_range + rx_range;
				}

				deg_range = max_range / 57.0;

				// No more than 8 degs
				deg_limit = 3.5;

				if (std::fabs(tx_site[z].lat) < 70.0) {
					deg_range_lon = deg_range / std::cos(DEG2RAD * tx_site[z].lat);
				}
				else {
					deg_range_lon = deg_range / std::cos(DEG2RAD * 70.0);
				}

				/* Correct for squares in degrees not being square in miles */

				deg_range = std::min(deg_range, deg_limit);
				deg_range_lon = std::min(deg_range_lon, deg_limit);

				const double nortRxHin = static_cast<int>(std::floor(tx_site[z].lat - deg_range));
				const double nortRxHax = static_cast<int>(std::floor(tx_site[z].lat + deg_range));

				double west_min = static_cast<int>(std::floor(tx_site[z].lon - deg_range_lon));

				while (west_min < 0) {
					west_min += 360;
				}

				while (west_min >= 360) {
					west_min -= 360;
				}

				double west_max = static_cast<int>(std::floor(tx_site[z].lon + deg_range_lon));

				while (west_max < 0) {
					west_max += 360;
				}

				while (west_max >= 360) {
					west_max -= 360;
				}

				min_lat = std::min(min_lat, nortRxHin);
				max_lat = std::max(max_lat, nortRxHax);

				if (LonDiff(west_min, min_lon) < 0.0) {
					min_lon = west_min;
				}

				if (LonDiff(west_max, max_lon) >= 0.0) {
					max_lon = west_max;
				}
			}

			/* Load any additional SDF files, if required */

			if(result = Input::LoadTopoData(max_lon, min_lon, max_lat, min_lat); result != 0 ){
				// This only fails on errors loading SDF tiles
				std::println(stderr, "Error loading topo data");
				return result;
			}
		}
		ppd=static_cast<double>(ippd);
		yppd=ppd; 

		Output::width = static_cast<unsigned>(ippd * ReduceAngle(max_west - min_west));
		Output::height = static_cast<unsigned>(ippd * ReduceAngle(max_north - min_north));
	}

	dpp = 1 / ppd;
	mpi = ippd-1; 

	// User defined clutter file
	if( udt_file != nullptr && (result = Input::LoadUDT(udt_file)) != 0 ){
		std::println(stderr, "Error loading clutter file");
		return result;
	}

	// Enrich with Clutter
	if(!clutter_file.empty()){
		/*
		Clutter tiles cover 16 x 12 degs but we only need a fraction of that area.
		Limit by max_range / miles per degree (at equator)
		*/
		if(result = Input::loadClutter(clutter_file,max_range/45,tx_site[0]); result != 0 ){
			std::println(stderr, "Error, invalid or clutter file not found");
			return result;
		}
	}

	if (max_range > 100 || LR.frq_mhz == 446.446) {  // Huh?
		cropping=false;
	}

	if (ppa == 0) {
	  if (propmodel == 2) {  // Modl 2 = LOS
			cropping = false;
			LOS::PlotLOSMap(tx_site[0], altitudeLR, ano_filename, use_threads);
			Output::DoLOS(mapfile, kml, ngs, tx_site);
		} else {
			// 90% of effort here
			LOS::PlotPropagation(tx_site[0], altitudeLR, ano_filename, propmodel, knifeedge, haf, pmenv, use_threads);

			if (debug) {
				std::println(stderr,"Finished PlotPropagation()");
			}	

			// nearfield void

			for (float x=-0.001; x<0.001;x=x+0.0001){
			        for (float y=-0.001; y<0.001;y=y+0.0001){
				        if(GetSignal(tx_site[0].lat+y, tx_site[0].lon+x)<=0) {
					        PutSignal(tx_site[0].lat+y, tx_site[0].lon+x, hottest);
					}
				}
			}

			if (cropping) {
				// CROPPING Factor determined in propPathLoss().
				// cropLon is the circle radius in pixels at it's widest (east/west) 
				cropLon*=dpp; // pixels to degrees
				max_north=cropLat; // degrees
				max_west=cropLon+tx_site[0].lon; // degrees west (positive)
				cropLat-=tx_site[0].lat; // angle from tx to edge

			
				if (debug) {
					std::println(stderr,"Cropping 1: max_west: {:.4f} cropLat: {:.4f} cropLon: {:.4f} longitude: {:.5f} dpp {:.7f}",max_west,cropLat,cropLon,tx_site[0].lon,dpp);
				}
				Output::width=static_cast<int>((cropLon*ppd)*2);
				Output::height=static_cast<int>((cropLat*ppd)*2);

				if (debug) {
					std::println(stderr,"Cropping 2: max_west: {:.4f} cropLat: {:.4f} cropLon: {:.7f} longitude: {:.5f} width {}",max_west,cropLat,cropLon,tx_site[0].lon,Output::width);
				}
				if (Output::width > 3600 * 10 || cropLon < 0) {
				  std::println(stderr,"FATAL BOUNDS! max_west: {:.4f} cropLat: {:.4f} cropLon: {:.7f} longitude: {:.5f}",max_west,cropLat,cropLon,tx_site[0].lon);
				  return 0;
				}
			}

			// Write bitmap
			if (LR.erp == 0.0) {
				Output::DoPathLoss(mapfile, geo, kml, ngs, tx_site);
			}
			else if (dbm) {
				Output::DoRxdPwr((to_stdout ? "" : mapfile), kml, ngs, tx_site);
			}
			else {
				if (result = Output::DoSigStr(mapfile, kml, ngs, tx_site); result != 0) {
					return result;
				}
			}
		}
		/*if(lidar){
			east=eastoffset;
			west=westoffset;
		}*/

		if (tx_site[0].lon > 0.0) {
			tx_site[0].lon *= -1;
		}

		if (tx_site[0].lon < -180.0) {
			tx_site[0].lon += 360;
		}

		if (cropping) {
			std::print(stderr, "|{:.6f}", tx_site[0].lat+cropLat);
			std::print(stderr, "|{:.6f}", tx_site[0].lon+cropLon);
			std::print(stderr, "|{:.6f}", tx_site[0].lat-cropLat);
			std::print(stderr, "|{:.6f}|",tx_site[0].lon-cropLon);
		} else {
			std::print(stderr, "|{:.6f}", max_north);
			std::print(stderr, "|{:.6f}", east);
			std::print(stderr, "|{:.6f}", min_north);
			std::print(stderr, "|{:.6f}|",west);
		}
		std::println(stderr, "");

	} else {
		strncpy(tx_site[0].name, "Tx", 3);
		strncpy(tx_site[1].name, "Rx", 3);
		LOS::PlotPath(tx_site[0], tx_site[1], 1);
		auto e = Output::PathReport(tx_site[0], tx_site[1], tx_site[0].filename, 0, propmodel, pmenv, rxGain);
		// Order flipped for benefit of graph. Makes no difference to data.
		Output::SeriesData(tx_site[1], tx_site[0], tx_site[0].filename, true, normalise);
	}

	return 0;
}
